# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication

from PyQt5.QtWidgets import QWidget
# from PyQt5.Qt import QApplication
from PyQt5.Qt import QWidget


import sys

app = QApplication(sys.argv)

window = QtWidgets.QWidget()
window.setWindowTitle("我是窗口")
window.resize(500, 500)
window.move(100, 100)
window.show()
#
# print(QWidget.__module__)
# print(QWidget.__mro__)
# print(QWidget.mro())
# print(QWidget.__class__)


sys.exit(app.exec_())




